<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class OrderCreateRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'buy_place' =>['required'],
            'status' => ['required'],
            'payment_method'=>['required'],
            'product[*][id]' =>['required'],
            'product[*][qty]' =>['required'],
            'customer_email'=>['email', 'required_if:buy_place, "online"'],
            'deliver_to'=>['required_if:buy_place,"online"']
        ];
    }

    public function messages()
    {
        return parent::messages(); // TODO: Change the autogenerated stub
    }
}
